site_name: OSCAR Documentation
repo_url: https://github.com/grycap/oscar
nav:
- Introduction: index.md
- Getting started:
  - Local testing: local-testing.md
  - Deployment with IM Dashboard: deploy-im-dashboard.md
  - Deployment with EC3: deploy-ec3.md
  - Deployment with Helm: deploy-helm.md
  - Deployment on K3s with Ansible: deploy-ansible.md
- Third party integrations:
  - Integration with EGI: egi-integration.md
  - OIDC Authorization: oidc-auth.md
  - Integration with SCONE: sgx-integration.md
  - Interlink: interlink_integration.md
- usage.md
- invoking.md
- Functions Definition Language (FDL): fdl.md
- FDL Composer: fdl-composer.md
- oscar-cli.md
- OpenAPI Specification: api.md
- Multitenancy: multitenancy.md
- Expose services: expose_services.md
- MinIO bucket replication: minio-bucket-replication.md
- Frequently Asked Questions (FAQ): faq.md
- license.md
- about.md
theme:
  favicon: images/logo.png
  logo: images/logo.png
  name: material
  palette:
    primary: teal
plugins:
- search
- render_swagger
copyright: "&copy; 2022, GRyCAP - i3M - Universitat Politècnica de València, Spain."